- converted the inputs file to a true data file; moved the setup and teardown to bart_fixture.sh, and the new file has the static output of the erstwhile getinputs() - as a result, added default setup and teardown functions if no bart_fixture.sh - also as a result, converted the main loop to do newline processing instead of array traversal - changed from $exec $inp to a single $cmd. this was because the old way never actually worked for multiple args anyway; and this seems like the only way to compose a command from multiple sources. in our case, the executable comes from the command line and the inputs come from a config file(inputs)

diff --git a/bart b/bart
--- a/bart
+++ b/bart
@@ -5,52 +5,67 @@
 
 set -u # defensive coding
 
-set -e # error out if inputs has syntax errors.
-source inputs
-set +e # turn error checking off so test runs' returns can be read
+set -e # error out if fixture code has syntax errors.
+if [ -e 'bart_fixture.sh' ]; then
+  source bart_fixture.sh
+else
+    function setup()
+    {
+      #cannot have an empty function, so putting a safe command
+      echo "setup"
+    }
+    
+    function teardown()
+    {
+      #cannot have an empty function, so putting a safe command
+      echo "teardown"
+    }
+fi
 
+set +e # turn error checking off so test runs' returns can be read
 
 function main()
 {
-		if ! getinputs; then
-			echo Error processing inputs. exiting
-			exit 1
+		if [[ $# -ne 2 ]]; then
+			echo "Usage: bart command inputfile"
+      exit 1
 		fi
+    local executable=$1
+    local inputfile=$2
 
-		if [[ ${#INPUTS[*]} -le 0 ]]; then
-			echo no inputs found. exiting
+		if [ ! -e "$inputfile" ]; then
+			echo $inputfile not found. exiting
       exit 1
 		fi
 
-		if [[ $# -eq 0 ]]; then
-			echo "Usage: bart <executable or quoted command>"
-      exit 2
-		fi
+    bart_banner
+
+    #newline code from http://gslsrc.net/l007_loops_in_bash.html & http://superuser.com/questions/284187/bash-iterating-over-lines-in-a-variable
+    orig_IFS="$IFS"
+    IFS=$'\n'
     
-    local executable=$1
-
-		bart_banner
-		echo ${INPUTS[*]}
-
-		for inp in ${INPUTS[*]}; do
+		for inp in `cat $inputfile`; do
 			setup
 			
 			OUTCOME=
-      echo Running: $executable $inp
-			$executable $inp
+      cmd="$executable $inp"
+      echo Running: $cmd
+			eval $cmd
       ret=$?
       
-      check_for_expected $executable $inp
+      check_for_expected $cmd
       if [[ ! $OUTCOME ]]; then
-        ask_and_add_result $executable $inp $ret
+        ask_and_add_result $cmd $ret
       fi
 			#echo outcome:$OUTCOME
 			# outcome is set by either check_for_expected or ask_and_add_result
-			print_outcome $executable $inp $ret $OUTCOME
-      store_for_summary $executable $inp $ret $OUTCOME
+			print_outcome $cmd $ret $OUTCOME
+      store_for_summary $executable $ret $OUTCOME
 			
 			teardown
     done
+    IFS=$orig_IFS
+    
     print_summary $executable
     bart_credits
 }
@@ -69,8 +84,7 @@ BART_TEST_LOGFILE="./bart_test_log.tsv"
 
 function check_for_expected()
 {
-  local executable=$1
-  local inp=$2
+  local cmd=$1
 
   EXPECTED_RET=
 
@@ -78,14 +92,14 @@ function check_for_expected()
     touch $BART_TEST_LOGFILE
   fi
   # find previous result
-  prev=`grep "$executable $inp" $BART_TEST_LOGFILE`
+  prev=`grep $cmd $BART_TEST_LOGFILE`
   #echo previous result line: $prev
   if [[ ! $prev ]]; then
     return
   fi
   
   EXPECTED_RET=`echo "$prev" | cut -f2`
-  #echo expected result: abc${EXPECTED_RET}xx
+  #echo expected result: ${EXPECTED_RET}
   if [[ $EXPECTED_RET -eq $ret ]]; then
   	OUTCOME=PASSED
   else
@@ -95,23 +109,22 @@ function check_for_expected()
 
 function ask_and_add_result()
 {
-	local executable=$1
-  local inp=$2
-  local ret=$3
+	local cmd=$1
+  local ret=$2
 
 	if [[ $ret -eq 127 ]]; then
-		echo "Ran command: \"$executable $inp\", which failed. Do you want to continue with the next run(c) or quit(q)?"
+		echo "Ran command: \"$cmd\", which failed. Do you want to continue with the next run(c) or quit(q)?"
 	  read ans_proceed	# add -n1 to make it an instant response
 	  if [ $ans_proceed != "c" -o $ans_proceed != "C" ]; then
 			exit 3	# TODO: fix this to skip this iteration, not the whole process.
 		fi
 	fi
 	echo
-  echo "Ran command: \"$executable $inp\", which returned: $ret. Is this the expected result (y/n)?"
+  echo "Ran command: \"$cmd\", which returned: $ret. Is this the expected result (y/n)?"
   read answer	# add -n1 to make it an instant response
   if [ $answer == "y" -o $answer == "Y" ]; then
 		#careful with the line below. There's supposed to be a tab between the command and the return value. Some editors convert tabs to spaces.
-    echo "$executable $inp	$ret" >> $BART_TEST_LOGFILE
+    echo "$cmd	$ret" >> $BART_TEST_LOGFILE
 		OUTCOME=PASSED
 		return
   fi
@@ -125,10 +138,9 @@ OUTCOMES=(  )
 
 function print_outcome()
 {
-    local executable=$1
-		local input=$2
-		local ret=$3
-    local outcome=$4
+    local cmd="$1"
+		local ret=$2
+    local outcome=$3
 
 		case $outcome in
 			PASSED )
@@ -138,14 +150,14 @@ function print_outcome()
 				outcome_str="\033[0;31mFAILED\033[0m"
 				;;
 		esac
-    echo -e "execution: \"$executable $input\", return: $ret, outcome: $outcome_str"
+    echo -e "execution of: \"$cmd\" returned: $ret and outcome: $outcome_str"
 }
 
 function store_for_summary()
 {
-  EXECUTIONS[${#EXECUTIONS[@]}]="$1	$2"
-  RETURNVALUES[${#RETURNVALUES[@]}]="$3"
-  OUTCOMES[${#OUTCOMES[@]}]="$4"
+  EXECUTIONS[${#EXECUTIONS[@]}]=$1
+  RETURNVALUES[${#RETURNVALUES[@]}]="$2"
+  OUTCOMES[${#OUTCOMES[@]}]="$3"
 
 }
 
@@ -164,4 +176,3 @@ function print_summary()
   done
 }
 main $*
-
